### ISSUE TITLE
no way back after cloning a profile

### ISSUE THREAD

**Issue by matthewfischer** [digitalrebar/provision#474] opened 2017-10-09 21:36 UTC
After cloning a profile and editing the name and clicking Add (which should probably be "Save" by thats another issue), there's no way back. You can see the new profile but can't close it. The only way out is to click on an unrelated category (like Machines), then back into Plugins.

<img width="1089" alt="screen shot 2017-10-09 at 3 31 56 pm" src="https://user-images.githubusercontent.com/1686293/31359525-8cdbe60e-ad07-11e7-8606-0758add5fce9.png">

**Comment by zehicle** [comment] 2017-12-12 15:34
duplicate of #504

**Comment by sygibson** [comment] 2017-12-20 14:59
@matthewfischer - I'm closing this issue, since it's a duplicate of #504 We're still addressing the problem, but under that issue.

**Closed by sygibson** 2017-12-20 14:59 UTC
Labels: provision-ux-bug
