### ISSUE TITLE
exploded isos will not be removed

### ISSUE THREAD

**Issue by mash-graz** [digitalrebar/provision#853] opened 2018-05-07 10:47 UTC
when i use `drpcli isos destroy ...` command, this file gets removed, but the exploded directory in `tftpboot` still exists. is there any command available to force a more adequate cleanup?

**Comment by galthaus** [comment] 2018-05-07 13:53
The iso gets destroyed, but the tftpboot doesn't because that directory is shared and not directly tied to iso image (because of versioning differences).  Also, a single iso could be exploded to multiple directories.   

Will need to think about this some more.

**Comment by galthaus** [comment] 2018-05-07 14:15
This is also a duplicate of #437

**Closed by galthaus** 2018-05-07 14:15 UTC
