### ISSUE TITLE
old bsdtar on Mac causes isos to not explode properly - update to 3.3+ bsdtar (homebrew)

### ISSUE THREAD

**Issue by drnic** [digitalrebar/provision#113] opened 2019-11-28 01:21 UTC
When I boot my nodes, they are failing to find the netboot files from tftpboot.

For both centos-7-install:

<img width="737" alt="Screen Shot 2019-11-28 at 10 52 40 am" src="https://user-images.githubusercontent.com/108/69769450-a0640280-11d0-11ea-820d-b31b0f59f8d3.png">

And ubuntu-18:

<img width="750" alt="Screen Shot 2019-11-28 at 10 29 54 am" src="https://user-images.githubusercontent.com/108/69769458-a823a700-11d0-11ea-88b3-31cde8b67bd9.png">

I ran the various commands in the docs to `drpcli bootenvs uploadiso ubuntu-18.04-install` but all I see are some almost empty `install` directories The documentation says I should see the ISOs exploded into `tftpboot` directory:

> The `uploadiso` command will fetch the ISO image as specified in the BootEnv JSON spec, download it, and then “explode” it in to the `drp-data/tftpboot/` directory for installation use.

https://provision.readthedocs.io/en/latest/doc/quickstart.html#install-boot-environments-bootenvs

```
$ sudo tree drp-data/tftpboot/ubuntu-18.04
drp-data/tftpboot/ubuntu-18.04
├── arm64
│   └── install
└── install
$ sudo tree drp-data/tftpboot/centos-7
drp-data/tftpboot/centos-7
├── arm64
│   └── install
└── install
```

The files that are created into these directories are:

```
➜  drp-home sudo ls -alR drp-data/tftpboot/centos-7
total 0
drwx------   4 root  staff   128 28 Nov 10:51 .
drwx------  33 root  staff  1056 28 Nov 10:45 ..
drwx------   3 root  staff    96 28 Nov 10:45 arm64
drwx------   3 root  staff    96 28 Nov 10:51 install

drp-data/tftpboot/centos-7/arm64:
total 0
drwx------  3 root  staff   96 28 Nov 10:45 .
drwx------  4 root  staff  128 28 Nov 10:51 ..
drwx------  3 root  staff   96 28 Nov 10:45 install

drp-data/tftpboot/centos-7/arm64/install:
total 8
drwx------  3 root  staff  96 28 Nov 10:45 .
drwx------  3 root  staff  96 28 Nov 10:45 ..
-rw-------  1 root  staff  64 28 Nov 10:45 .centos-7.rebar_canary

drp-data/tftpboot/centos-7/install:
total 8
drwx------  3 root  staff   96 28 Nov 10:51 .
drwx------  4 root  staff  128 28 Nov 10:51 ..
-rw-------  1 root  staff   64 28 Nov 10:51 .centos-7.rebar_canary

$ sudo cat drp-data/tftpboot/centos-7/install/.centos-7.rebar_canary
9a2c47d97b9975452f7d582264e9fc16d108ed8252ac6816239a3b58cef5c53d
```

I don't see anything in `drp.log` about an error during `drpcli bootenvs uploadiso ubuntu-18.04-install`.

Any protips to debug this error?

**Comment by zehicle** [comment] 2019-11-28 03:13
What is your DRP host environment?  Are you running on ARM?RackN.com 512.773.7533
-------- Original message --------From: Dr Nic Williams <notifications@github.com> Date: 11/27/19  7:21 PM  (GMT-06:00) To: digitalrebar/provision <provision@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [digitalrebar/provision] Netboot files missing from tftpboot for ISOs (#113) When I boot my nodes, they are failing to find the netboot files from tftpboot:

For both centos-7-install:



And ubuntu-18:



I ran the various commands in the docs to drpcli bootenvs uploadiso ubuntu-18.04-install but all I see are some empty install files.

https://provision.readthedocs.io/en/latest/doc/quickstart.html#install-boot-environments-bootenvs

$ sudo tree drp-data/tftpboot/ubuntu-18.04

drp-data/tftpboot/ubuntu-18.04

├── arm64

│   └── install

└── install

$ sudo tree drp-data/tftpboot/centos-7

drp-data/tftpboot/centos-7

├── arm64

│   └── install

└── install



The files that are created into these directories are:

➜  drp-home sudo ls -alR drp-data/tftpboot/centos-7

total 0

drwx------   4 root  staff   128 28 Nov 10:51 .

drwx------  33 root  staff  1056 28 Nov 10:45 ..

drwx------   3 root  staff    96 28 Nov 10:45 arm64

drwx------   3 root  staff    96 28 Nov 10:51 install



drp-data/tftpboot/centos-7/arm64:

total 0

drwx------  3 root  staff   96 28 Nov 10:45 .

drwx------  4 root  staff  128 28 Nov 10:51 ..

drwx------  3 root  staff   96 28 Nov 10:45 install



drp-data/tftpboot/centos-7/arm64/install:

total 8

drwx------  3 root  staff  96 28 Nov 10:45 .

drwx------  3 root  staff  96 28 Nov 10:45 ..

-rw-------  1 root  staff  64 28 Nov 10:45 .centos-7.rebar_canary



drp-data/tftpboot/centos-7/install:

total 8

drwx------  3 root  staff   96 28 Nov 10:51 .

drwx------  4 root  staff  128 28 Nov 10:51 ..

-rw-------  1 root  staff   64 28 Nov 10:51 .centos-7.rebar_canary



I don't see anything in drp.log about an error during drpcli bootenvs uploadiso ubuntu-18.04-install.

Any protips to debug this error?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/digitalrebar/provision/issues/113?email_source=notifications\u0026email_token=AAFQ7VEYPMTPNYLACW6PHS3QV4MJ3A5CNFSM4JSOBGS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H4RXC4Q",

"url": "https://github.com/digitalrebar/provision/issues/113?email_source=notifications\u0026email_token=AAFQ7VEYPMTPNYLACW6PHS3QV4MJ3A5CNFSM4JSOBGS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H4RXC4Q",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by drnic** [comment] 2019-11-28 03:22
Err, sorry for not including that.

Running MacOS 10.14.6
```
$ uname -a
Darwin starkair.lan 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
```

**Comment by galthaus** [comment] 2019-11-28 03:32
I fixed this today.  You will need drp-tip.  v4.1.4-dev.6

**Comment by drnic** [comment] 2019-11-28 03:34
@galthaus I did try tip:

```
$ head drp.log
dr-provision2019/11/28 02:30:41.283875 Processing arguments
dr-provision2019/11/28 02:30:41.283978 Version: v4.1.4-dev.6+geb2e6bbe46c955dcfdb77003c12a7920ade0cf1e
```

But...
```
sudo ls -la drp-data/tftpboot/ubuntu-18.04/install
total 0
drwx------  3 drnic  staff   96 28 Nov 12:53 .
drwx------  4 drnic  staff  128 28 Nov 12:53 ..
-rw-------  1 drnic  staff    0 28 Nov 12:53 .ubuntu-18.04.rebar_canary
```

**Comment by galthaus** [comment] 2019-11-28 04:24
Okay - my previous comment was wrong.  This is one a Mac so Darwin use case.

The issue is that bsdtar was old and need to be update with home-brew.  We should check in install.sh and explode_iso.sh for at least version 3.3 of bsdtar on Darwin and fail otherwise.

**Comment by galthaus** [comment] 2019-11-28 04:26
https://provision.readthedocs.io/en/latest/doc/install.html#prerequisites - for docs until checks can be added to code.

**Comment by galthaus** [comment] 2019-12-03 21:12
Addressed in the next release of DRP server.  it will not if bsdtar is not at the correct version.

**Comment by galthaus** [comment] 2019-12-03 21:12
v4.1.4 or beyond.

**Closed by galthaus** 2019-12-03 21:12 UTC
